"""init

Revision ID: bf22a6e45d7e
Revises: 
Create Date: 2022-06-12 20:09:07.933867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf22a6e45d7e'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('ext_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places')),
    sa.UniqueConstraint('ext_id', name=op.f('uq_places_ext_id'))
    )
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ext_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenes')),
    sa.UniqueConstraint('ext_id', name=op.f('uq_scenes_ext_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ext_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('ext_id', name=op.f('uq_users_ext_id'))
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ext_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_visits_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits')),
    sa.UniqueConstraint('ext_id', name=op.f('uq_visits_ext_id'))
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('guid', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('camera', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_documents_place_id_places')),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_documents_scene_id_scenes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_documents_visit_id_visits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('guid', name=op.f('uq_documents_guid'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('visits')
    op.drop_table('users')
    op.drop_table('scenes')
    op.drop_table('places')
    # ### end Alembic commands ###
